# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-sicilian-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6.1
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  # TODO nf-core: Add required software dependencies here
  - conda-forge::numpy=1.19.5
  - conda-forge::pandas=1.1.5
  - conda-forge::pyarrow=0.13.0
  - bioconda::pysam=0.16.0
  - biocondaa::samtools=1.10
  - conda-forge::gawk=5.1.0
  - bioconda::star=2.7.5a 